# Generated by Django 6.0.3 on 2026-04-02 05:39

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gid_2', models.CharField(db_index=True, max_length=30, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('iso3', models.CharField(db_index=True, max_length=3)),
                ('admin1_name', models.CharField(max_length=200)),
                ('admin2_name', models.CharField(max_length=200)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('pop_total', models.IntegerField(default=0)),
                ('area_km2', models.FloatField(default=0)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin Unit',
                'ordering': ['iso3', 'admin1_name', 'admin2_name'],
            },
        ),
        migrations.CreateModel(
            name='ForecastRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('forecast_date', models.DateField(db_index=True)),
                ('issued_at', models.DateTimeField()),
                ('lead_time_days', models.IntegerField(default=7)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('extracting', 'Extracting'), ('processing', 'Processing'), ('triggering', 'Evaluating Triggers'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('source_file', models.CharField(blank=True, max_length=500)),
                ('stations_processed', models.IntegerField(default=0)),
                ('alerts_generated', models.IntegerField(default=0)),
                ('log', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-forecast_date'],
                'get_latest_by': 'forecast_date',
            },
        ),
        migrations.CreateModel(
            name='HazardType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('return_periods', models.JSONField(default=list, help_text='e.g. [10, 20, 50, 75, 100]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ForecastStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('station_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('river', models.CharField(blank=True, max_length=200)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('rp_thresholds', models.JSONField(default=dict, help_text='Discharge thresholds: {"10": 1200, "20": 1800, ...}')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affected_units', models.ManyToManyField(blank=True, related_name='upstream_stations', to='ibf.adminunit')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TriggerThreshold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('country', 'Country-level'), ('admin1', 'Province-level'), ('admin2', 'District-level')], default='country', max_length=10)),
                ('iso3', models.CharField(blank=True, db_index=True, max_length=3)),
                ('severity', models.CharField(choices=[('watch', 'Watch'), ('warning', 'Warning'), ('alert', 'Alert')], max_length=10)),
                ('min_return_period', models.IntegerField()),
                ('min_pop_exposed', models.IntegerField(default=0)),
                ('min_probability', models.FloatField(default=0.5)),
                ('min_lead_time_days', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ibf.adminunit')),
                ('hazard_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='ibf.hazardtype')),
            ],
            options={
                'ordering': ['hazard_type', 'severity'],
            },
        ),
        migrations.CreateModel(
            name='ImpactEstimate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_period', models.IntegerField(db_index=True)),
                ('pop_exposed', models.IntegerField(default=0)),
                ('pop_exposed_pct', models.FloatField(default=0)),
                ('flood_area_km2', models.FloatField(default=0)),
                ('area_flooded_pct', models.FloatField(default=0)),
                ('mean_depth_m', models.FloatField(default=0)),
                ('cropland_flooded_km2', models.FloatField(default=0)),
                ('extra_metrics', models.JSONField(blank=True, default=dict)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('admin_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impacts', to='ibf.adminunit')),
                ('hazard_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impacts', to='ibf.hazardtype')),
            ],
            options={
                'ordering': ['admin_unit', 'return_period'],
                'indexes': [models.Index(fields=['hazard_type', 'return_period'], name='ibf_impacte_hazard__61c902_idx')],
                'unique_together': {('admin_unit', 'hazard_type', 'return_period')},
            },
        ),
        migrations.CreateModel(
            name='StationForecast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lead_time_days', models.IntegerField()),
                ('discharge_m3s', models.FloatField()),
                ('discharge_max_m3s', models.FloatField(blank=True, null=True)),
                ('discharge_min_m3s', models.FloatField(blank=True, null=True)),
                ('derived_rp', models.IntegerField(blank=True, null=True)),
                ('probability_above_rp', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forecast_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_forecasts', to='ibf.forecastrun')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='ibf.forecaststation')),
            ],
            options={
                'ordering': ['station', 'lead_time_days'],
                'unique_together': {('forecast_run', 'station', 'lead_time_days')},
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='issued', max_length=12)),
                ('severity', models.CharField(choices=[('watch', 'Watch'), ('warning', 'Warning'), ('alert', 'Alert')], max_length=10)),
                ('return_period', models.IntegerField()),
                ('lead_time_days', models.IntegerField()),
                ('discharge_m3s', models.FloatField()),
                ('probability', models.FloatField()),
                ('pop_exposed', models.IntegerField(default=0)),
                ('pop_exposed_pct', models.FloatField(default=0)),
                ('flood_area_km2', models.FloatField(default=0)),
                ('cropland_flooded_km2', models.FloatField(default=0)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='ibf.adminunit')),
                ('forecast_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='ibf.forecastrun')),
                ('hazard_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='ibf.hazardtype')),
                ('threshold', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ibf.triggerthreshold')),
            ],
            options={
                'ordering': ['-issued_at', '-severity'],
                'indexes': [models.Index(fields=['status', 'severity'], name='ibf_alert_status_b10584_idx'), models.Index(fields=['admin_unit', 'status'], name='ibf_alert_admin_u_3ea32f_idx')],
            },
        ),
    ]
